- hosts: localhost
  vars_files:
    - vars/aws-creds.yml
    - vars/instance_vars.yml
  vars:
    instance_names:
      - jenkins-server
      - sonar-server
      - nexus-server
      - monitoring-server

  tasks:
    - name: "Install python3"
      package:
        name: python3-pip
        state: present

    - name: "Install Boto3"
      pip:
        name: boto3

    - name: "Provisioning Ec2 instance"
      community.aws.ec2_instance:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        region: "{{ region }}"
        count: "{{ instance_names | length}}"
        name: "{{ item }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ key }}"
        vpc_subnet_id: "{{ subnet }}"
        security_group: default
        network_interfaces:
          - assign_public_ip: true
        image_id: "{{ image }}"
      loop: "{{ instance_names }}"
      register: ec2

    - set_fact:
        private_ip: "{{ ec2.instances | map(attribute='private_ip_address') | list }}"

    - debug:
        var: private_ip
    - template:
        src: /template/inventory.j2
        dest: inventory.ini
