route:
  receiver: "email"
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

  routes:
    # 🔴 Critical Alerts from Production
    - match:
        severity: critical
        cluster: prod
      receiver: email

    # 🟠 Warnings from Dev
    - match:
        severity: warning
        cluster: dev
      receiver: email

    # 🔵 All Other Alerts
    - receiver: email

receivers:
  - name: "email"
    email_configs:
      - to: "your-email@gmail.com"
        from: "your-gmail@gmail.com"
        smarthost: "smtp.gmail.com:587"
        auth_username: "your-gmail@gmail.com"
        auth_identity: "your-gmail@gmail.com"
        auth_password: "your-app-password"
        send_resolved: true
